load("@rules_flutter//flutter:defs.bzl", "dart_format_test", "flutter_analyze_test", "flutter_library")

flutter_library(
    name = "flutter_razemify",
    srcs = glob(["lib/**"]),
    pubspec = "pubspec.yaml",
    visibility = ["//visibility:public"],
    deps = [
        "@flutter_razemify_deps//:all",
        "@flutter_sdk//flutter/packages/flutter",
    ],
)

flutter_library(
    name = "flutter_razemify_android_debug",
    srcs = glob([
        "android/**",
        "lib/**",
    ]),
    generated_srcs = {
        "//flutter_razemify/rust:flutter_razemify_arm64_v8a": "android/src/main/jniLibs/arm64-v8a",
    },
    pubspec = "pubspec.yaml",
    visibility = ["//visibility:public"],
    deps = [
        "@flutter_razemify_deps//:all",
        "@flutter_sdk//flutter/packages/flutter",
    ],
)

flutter_library(
    name = "flutter_razemify_android_release",
    srcs = glob([
        "android/**",
        "lib/**",
    ]),
    generated_srcs = {
        "//flutter_razemify/rust:flutter_razemify_arm64_v8a": "android/src/main/jniLibs/arm64-v8a",
        "//flutter_razemify/rust:flutter_razemify_armeabi_v7a": "android/src/main/jniLibs/armeabi-v7a",
        "//flutter_razemify/rust:flutter_razemify_x86": "android/src/main/jniLibs/x86",
        "//flutter_razemify/rust:flutter_razemify_x86_64": "android/src/main/jniLibs/x86_64",
    },
    pubspec = "pubspec.yaml",
    visibility = ["//visibility:public"],
    deps = [
        "@flutter_razemify_deps//:all",
        "@flutter_sdk//flutter/packages/flutter",
    ],
)

flutter_analyze_test(
    name = "analyze",
    srcs = ["analysis_options.yaml"],
    embed = [":flutter_razemify"],
)

dart_format_test(
    name = "format",
    srcs = glob(["lib/**/*.dart"]),
)
