load(
    "//bazel:defs.bzl",
    "dart_analysis_options",
    "dart_analyze_test",
    "dart_format_test",
    "flutter_plugin",
)

flutter_plugin(
    name = "flutter_razemify",
    srcs = glob(["lib/**/*.dart"]),
    package_name = "flutter_razemify",
    platforms = ["android"],
    visibility = ["//visibility:public"],
    deps = [
        "@flutter_razemify_deps//:ffi",
        "@flutter_razemify_deps//:flutter",
        "@flutter_razemify_deps//:image",
    ],
    native_deps = ["//flutter_razemify/rust:flutter_razemify_shared"],
)

dart_analysis_options(
    name = "analysis_options",
    src = "analysis_options.yaml",
    deps = ["@flutter_razemify_deps//:flutter_lints"],
)

dart_analyze_test(
    name = "analyze",
    options = ":analysis_options",
    target = ":flutter_razemify",
)

dart_format_test(
    name = "format",
    options = ":analysis_options",
    target = ":flutter_razemify",
)
